###
POST http://localhost:3000/category
Content-Type: application/json

{ "name": "Disk", "description": "test"}

###
DELETE http://localhost:3000/category/62d674dbf885ed2f334496d4


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{ "email": "test@gmail.com", "password": "test" }

###
DELETE http://localhost:3000/user/62d682b3727ebefe3d856f6c


###
POST http://localhost:3000/order
Content-Type: application/json

{
  "basket":[{
    "id":"1",
    "quantity":3
  },{
    "id":"2",
    "quantity":1
  }],
  "userId":1
}